import {isUndefinedOrNull} from '@type-editor/commons';
import type {PmTransaction} from '@type-editor/editor-types';

import {historyKey} from '../plugin/history-plugin-key';


/**
 * Returns true if the given transaction was generated by the history
 * plugin.
 *
 * @param transaction
 */
export function isHistoryTransaction(transaction: PmTransaction): boolean {
    return !isUndefinedOrNull(transaction.getMeta(historyKey));
}
